# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(757, 744)
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.routeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routeLabel.sizePolicy().hasHeightForWidth())
        self.routeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Eras Demi ITC")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.routeLabel.setFont(font)
        self.routeLabel.setObjectName("routeLabel")
        self.verticalLayout.addWidget(self.routeLabel)
        self.finderLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finderLabel.sizePolicy().hasHeightForWidth())
        self.finderLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Eras Demi ITC")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.finderLabel.setFont(font)
        self.finderLabel.setObjectName("finderLabel")
        self.verticalLayout.addWidget(self.finderLabel)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.year7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year7.sizePolicy().hasHeightForWidth())
        self.year7.setSizePolicy(sizePolicy)
        self.year7.setMinimumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.year7.setFont(font)
        self.year7.setObjectName("year7")
        self.gridLayout.addWidget(self.year7, 7, 0, 1, 1)
        self.oneRoute = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oneRoute.sizePolicy().hasHeightForWidth())
        self.oneRoute.setSizePolicy(sizePolicy)
        self.oneRoute.setMinimumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.oneRoute.setFont(font)
        self.oneRoute.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.oneRoute.setObjectName("oneRoute")
        self.gridLayout.addWidget(self.oneRoute, 7, 1, 1, 1)
        self.question = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question.sizePolicy().hasHeightForWidth())
        self.question.setSizePolicy(sizePolicy)
        self.question.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.question.setFont(font)
        self.question.setObjectName("question")
        self.gridLayout.addWidget(self.question, 6, 0, 1, 2)
        self.logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.logo.setObjectName("logo")
        self.gridLayout.addWidget(self.logo, 0, 1, 1, 1)
        MainMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainMenu)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Route Finder"))
        self.routeLabel.setText(_translate("MainMenu", "Route"))
        self.finderLabel.setText(_translate("MainMenu", "Finder"))
        self.year7.setText(_translate("MainMenu", "For a year 7 student"))
        self.oneRoute.setText(_translate("MainMenu", "Find a route from one room to another"))
        self.question.setText(_translate("MainMenu", "Is this for a year 7 pupil or any other student?"))
        self.logo.setText(_translate("MainMenu", "<html><head/><body><p><img src=\":/newPrefix/rsz_0wdggdhs_400x400.jpg\"/></p></body></html>"))

import l_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMenu = QtWidgets.QMainWindow()
    ui = Ui_MainMenu()
    ui.setupUi(MainMenu)
    MainMenu.show()
    sys.exit(app.exec_())

