# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'year7.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Year7(object):
    def setupUi(self, Year7):
        Year7.setObjectName("Year7")
        Year7.resize(579, 648)
        self.centralwidget = QtWidgets.QWidget(Year7)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.backButton.setObjectName("backButton")
        self.gridLayout_2.addWidget(self.backButton, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.question = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.question.setFont(font)
        self.question.setObjectName("question")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.question)
        self.question2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.question2.setFont(font)
        self.question2.setObjectName("question2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.question2)
        self.gridLayout_2.addLayout(self.formLayout, 1, 0, 1, 2)
        self.RouteOutput = QtWidgets.QTextEdit(self.centralwidget)
        self.RouteOutput.setMaximumSize(QtCore.QSize(500, 16777215))
        self.RouteOutput.setObjectName("RouteOutput")
        self.gridLayout_2.addWidget(self.RouteOutput, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.selectButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectButton.setMinimumSize(QtCore.QSize(0, 30))
        self.selectButton.setObjectName("selectButton")
        self.gridLayout.addWidget(self.selectButton, 1, 1, 1, 1)
        self.dayLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dayLabel.sizePolicy().hasHeightForWidth())
        self.dayLabel.setSizePolicy(sizePolicy)
        self.dayLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dayLabel.setFont(font)
        self.dayLabel.setObjectName("dayLabel")
        self.gridLayout.addWidget(self.dayLabel, 2, 0, 1, 1)
        self.dayBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dayBox.sizePolicy().hasHeightForWidth())
        self.dayBox.setSizePolicy(sizePolicy)
        self.dayBox.setMinimumSize(QtCore.QSize(0, 30))
        self.dayBox.setObjectName("dayBox")
        self.gridLayout.addWidget(self.dayBox, 3, 0, 1, 1)
        self.tutorGroupLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(119)
        sizePolicy.setHeightForWidth(self.tutorGroupLabel.sizePolicy().hasHeightForWidth())
        self.tutorGroupLabel.setSizePolicy(sizePolicy)
        self.tutorGroupLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tutorGroupLabel.setSizeIncrement(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tutorGroupLabel.setFont(font)
        self.tutorGroupLabel.setObjectName("tutorGroupLabel")
        self.gridLayout.addWidget(self.tutorGroupLabel, 0, 0, 1, 1)
        self.periodBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.periodBox.sizePolicy().hasHeightForWidth())
        self.periodBox.setSizePolicy(sizePolicy)
        self.periodBox.setMinimumSize(QtCore.QSize(0, 30))
        self.periodBox.setObjectName("periodBox")
        self.gridLayout.addWidget(self.periodBox, 3, 1, 1, 1)
        self.tutorPickCombo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tutorPickCombo.sizePolicy().hasHeightForWidth())
        self.tutorPickCombo.setSizePolicy(sizePolicy)
        self.tutorPickCombo.setMinimumSize(QtCore.QSize(0, 30))
        self.tutorPickCombo.setObjectName("tutorPickCombo")
        self.gridLayout.addWidget(self.tutorPickCombo, 1, 0, 1, 1)
        self.periodLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(119)
        sizePolicy.setHeightForWidth(self.periodLabel.sizePolicy().hasHeightForWidth())
        self.periodLabel.setSizePolicy(sizePolicy)
        self.periodLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.periodLabel.setFont(font)
        self.periodLabel.setObjectName("periodLabel")
        self.gridLayout.addWidget(self.periodLabel, 2, 1, 1, 1)
        self.WordButton = QtWidgets.QPushButton(self.centralwidget)
        self.WordButton.setMinimumSize(QtCore.QSize(0, 50))
        self.WordButton.setObjectName("WordButton")
        self.gridLayout.addWidget(self.WordButton, 4, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 1, 1, 1)
        Year7.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Year7)
        self.statusbar.setObjectName("statusbar")
        Year7.setStatusBar(self.statusbar)

        self.retranslateUi(Year7)
        QtCore.QMetaObject.connectSlotsByName(Year7)

    def retranslateUi(self, Year7):
        _translate = QtCore.QCoreApplication.translate
        Year7.setWindowTitle(_translate("Year7", "Route For Year 7"))
        self.backButton.setText(_translate("Year7", "Back"))
        self.question.setText(_translate("Year7", "What tutor group does the "))
        self.question2.setText(_translate("Year7", "student belong to?"))
        self.selectButton.setText(_translate("Year7", "Select"))
        self.dayLabel.setText(_translate("Year7", "Day"))
        self.tutorGroupLabel.setText(_translate("Year7", "Tutor Group"))
        self.periodLabel.setText(_translate("Year7", "Period"))
        self.WordButton.setText(_translate("Year7", "Save to word"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Year7 = QtWidgets.QMainWindow()
    ui = Ui_Year7()
    ui.setupUi(Year7)
    Year7.show()
    sys.exit(app.exec_())

